abstract class GetCarsBySearchException implements Exception{}

class FailureGetCarsBySearch extends GetCarsBySearchException{}

class NoInternetConnectionGetCarsBySearch extends GetCarsBySearchException{}